Add missing dependency on PHYLIB
To solve build error:
drivers/built-in.o: In function `aml_ethtool_op_set_eee':
crypto_dev.c:(.text+0x14bfc8): undefined reference to `phy_ethtool_set_eee'