config.meson8b: remove unused drivers
This removes unused drivers on our product.

CONFIG_HIBERNATION=n fixes a build problem since we don't have
the OSD driver.

  kernel/built-in.o: In function `hibernate':
  padata.c:(.text+0x3f944): undefined reference to `osd_init_progress_bar'