Force sound to be builtin
A few things now require the sound driver to be builtin.

drivers/built-in.o: In function `aml_sd_uart_detect':
crypto_dev.c:(.text+0x16d1bc): undefined reference to `ext_codec'
drivers/built-in.o: In function `aml_sduart_pre':
crypto_dev.c:(.text+0x16d2d8): undefined reference to `ext_codec'
drivers/built-in.o: In function `amhdmitx_remove':
crypto_dev.c:(.text+0x17e2e8): undefined reference to `aout_unregister_client'
drivers/built-in.o: In function `amhdmitx_probe':
crypto_dev.c:(.text+0x17f970): undefined reference to `aout_register_client'